bank-inmakes/banking_project/banking_app/urls.py
from django.urls import path
from . import views
app_name='bank'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout',views.logout,name='logout'),
    path('person-form/', views.person_form, name='person-form'),
    path('get-branches/', views.get_branches, name='get-branches')
    
    
]

bank-inmakes/banking_project/banking_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('banking_app.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bank-inmakes/banking_project/banking_app/models.py
from django.db import models

# Create your models here.
from django.db import models

class District(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Person(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    PAYMENT_METHOD_CHOICES = (
        ('cheque', 'Cheque'),
        ('debit', 'Debit Card'),
        ('credit', 'Credit Card'),
    )

    name = models.CharField(max_length=124)
    dob = models.DateField()  # Date of Birth
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.TextField()

    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True)
    
    payment_method = models.CharField(max_length=10, choices=PAYMENT_METHOD_CHOICES, default='cheque')

    def __str__(self):
        return self.name

bank-inmakes/banking_project/banking_app/forms.py
from django import forms
from .models import District, Branch, Person

class PersonForm(forms.ModelForm):
    district = forms.ModelChoiceField(queryset=District.objects.all())
    branch = forms.ModelChoiceField(queryset=Branch.objects.none())
    
    class Meta:
        model = Person
        fields = '__all__'

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    PAYMENT_METHOD_CHOICES = (
        ('cheque', 'Cheque'),
        ('debit', 'Debit Card'),
        ('credit', 'Credit Card'),
    )

    ACCOUNT_TYPE_CHOICES = (
        ('savings', 'Savings account'),
        ('current', 'Current account'),
    )

    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Name'
    )
    dob = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control'}),
        label='Date of Birth'
    )
    age = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        label='Age'
    )
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
        label='Gender'
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Phone Number'
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        label='Email'
    )
    address = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        label='Address'
    )
    district = forms.ModelChoiceField(
        queryset=District.objects.all(),
        widget=forms.Select(attrs={'class': 'form-select'}),
        label='District'
    )
    payment_method = forms.ChoiceField(
        choices=PAYMENT_METHOD_CHOICES,
        widget=forms.Select(attrs={'class': 'form-select dropdown'}),
        label='Payment Method'
    )
    
    account_type = forms.ChoiceField(
        choices=ACCOUNT_TYPE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-select dropdown'}),
        label='Account Type'
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branch.objects.filter(district_id=district_id)
            except (ValueError, TypeError):
                pass

bank-inmakes/banking_project/banking_app/views.py
# Create your views here.
from django.shortcuts import render, redirect
# from django.contrib import messages
# from .models import Customer
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

def home(request):
    return render(request, 'index.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid credentials')
            return redirect('/login')

    return render(request,'login.html')


def register(request):
    if request.method=='POST':
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        username=request.POST['username']
        email=request.POST['email']
        password=request.POST['password']
        cpassword=request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'username already taken')
                return redirect(".")
            elif User.objects.filter(email=email).exists():
                messages.info(request,'email id already taken')
                return redirect('.')
            else:
               user=User.objects.create_user(username=username,first_name=first_name,last_name=last_name,email=email,password=password)

               user.save()
               return redirect('/login')
        else:
            messages.info(request,'password not matching')
            return redirect('.')


    return render(request,'register.html')

def logout(request):
    auth.logout(request)
    return redirect('/')




# added
from django.shortcuts import render
from .forms import PersonForm
from django.http import JsonResponse
from .models import Branch

def person_form(request):
    if request.method == "POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()
            success_message = "Form submitted successfully!"
            return render(request, 'form.html', {'form': form,'success_message': success_message})
           
    else:
        form = PersonForm()
    
    return render(request, 'form.html', {'form': form,})

def get_branches(request):
    district_id = request.GET.get('district_id')
    branches = Branch.objects.filter(district_id=district_id).values("id", "name")
    return JsonResponse({"branches": list(branches)})

bank-inmakes/banking_project/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<!-- basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- mobile metas -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<!-- site metas -->
<title>Bankio | form</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content=""> 
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
<link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<style>
    .fixed-top-right {
    position: fixed;
    top: 0;
    right: 0;
    max-width: 750px;
    height: auto;
}
.form-control:focus {
  outline: none;
  border-color: #80bdff;
  box-shadow: 0 0 10px #80bdff;

}

</style>
</head>
<body>
  <!--header section start -->
  <div class="header_section">
    <div class="header_left">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="logo"><a href="{% url 'bank:home' %}"><img src="{% static 'images/logo.png'%}"></a></div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bank:home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
                                  <li class="nav-item nav-link">
                   Hello {{user.username}}
                  </li>
                                  <li class="nav-item">
                  <a class="nav-link" href="{% url 'bank:logout' %}">Logout</a>
                </li>
                                  {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bank:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bank:register' %}">Register</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBranches" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Branches
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownBranches">
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">ERNAKULAM</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">TRIVANDRUM</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">KOLLAM</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">KANNUR</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">KOTTAYAM</a>
              </div>
            </li>
            
          </ul>
        </div>
      </nav>
        
      
      
        <div class="container  mb-5" >
            <div class="row justify-content-center">
              <div class="col-md-10">
                <div class="login-box">
                    {% if success_message %}
            <div class="alert alert-success">{{ success_message }}</div>
            <a href="{% url 'bank:home' %}"><button type="submit" class="btn btn-info">Go To HomePage</button></a>
        {% endif %}
        <h1 class="banner_taital">Person Form</h1>
        <form action="" method="POST" id="my_form">
          {% csrf_token %}
          <div class="form-row">
                            
                            
                                <div class="col-md-7 mb-3">
                                  
                                    {% for field in form %}
                                        {% if field.name != 'gender' %}
                                            <div class="mb-3">
                                                <label class="form-label">{{ field.label }}</label>
                                                {{ field }}
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                <div class="col-md-4 ml-5 mb-3">
                                    {% for field in form %}
                                        {% if field.name == 'gender' %}
                                            <div class="mb-3">
                                                <label class="form-label">{{ field.label }}</label>
                                                <div style="margin-left: 20px;">
                                                {{ field }}
                                            </div>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                            
                            <button type="submit" class="btn btn-primary col-md-7">Save</button>
                          
                        </form>
                    </div>
                    
                    
                </div>
              </div>
            </div>
          </div>
          


    
    </div>

    
    <div class="header_right">
        <img src="{% static 'images/20943447.jpg' %}" class="banner_"style="position: absolute; top: 100px; right: 150px;width: 750px;" >
    </div>
    
    </div>
   
     <!--footer section start -->
     <div class="footer_section layout_padding">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-sm-6">
            <h4 class="about_text">About Financial</h4>
            <div class="location_text"><img src="{% static 'images/map-icon.png' %}"><span class="padding_left_15">Locations</span></div>
            <div class="location_text"><img src="{% static 'images/call-icon.png' %}"><span class="padding_left_15">+01 9876543210</span></div>
            <div class="location_text"><img src="{% static 'images/mail-icon.png' %}"><span class="padding_left_15">demo@gmail.com</span></div>
          </div>
          <div class="col-lg-3 col-sm-6">
            <h4 class="about_text">About Financial</h4>
            <p class="dolor_text">ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</p>
          </div>
          <div class="col-lg-3 col-sm-6">
            <h4 class="about_text">Instagram</h4>
            <div class="footer_images">
              <div class="footer_images_left">
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
              </div>
              <div class="footer_images_right">
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-sm-6">
            <h4 class="about_text">Newsletter</h4>
            <input type="text" class="mail_text" placeholder="Enter your email" name="Enter your email">
            <div class="subscribe_bt"><a href="#">Subscribe</a></div>
            <div class="footer_social_icon">
              <ul>
                <li><a href="#"><img src="{% static 'images/fb-icon1.png' %}"></a></li>
                <li><a href="#"><img src="{% static 'images/twitter-icon1.png' %}"></a></li>
                <li><a href="#"><img src="{% static 'images/linkedin-icon1.png' %}"></a></li>
                <li><a href="#"><img src="{% static 'images/youtub-icon1.png' %}"></a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- copyright section start -->
        <div class="copyright_section">
          <div class="copyright_text">Copyright 2019 All Right Reserved By <a href="https://html.design">Free HTML Templates</a></div>
        </div>
        <!-- copyright section end -->
      </div>
    </div>
    
    <!--footer section end -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script> 

   
 

    
    

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
    $(document).ready(function () {
        $("#id_district").change(function () {
            var districtId = $(this).val();
            $("#id_branch").empty();
            
            $.ajax({
                type: "GET",
                url: "{% url 'bank:get-branches' %}", // Replace with your view URL
                data: { district_id: districtId },
                success: function (data) {
                    $.each(data.branches, function (key, value) {
                        $("#id_branch").append(
                            $("<option></option>").attr("value", value.id).text(value.name)
                        );
                    });
                },
            });
        });
    });
    </script>
</body>
</html>

bank-inmakes/banking_project/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<!-- basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- mobile metas -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<!-- site metas -->
<title>Bankio | Login</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content=""> 
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
<link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<style>
    .fixed-top-right {
    position: fixed;
    top: 0;
    right: 0;
    max-width: 750px;
    height: auto;
}
.form-control:focus {
  outline: none;
  border-color: #80bdff;
  box-shadow: 0 0 10px #80bdff;
}
</style>
</head>
<body>
  <!--header section start -->
    <div class="header_section">
      <div class="header_left">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="logo"><a href="{% url 'bank:home' %}"><img src="{% static 'images/logo.png'%}"></a></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'bank:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'bank:register' %}">Register</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBranches" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Branches
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownBranches">
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">ERNAKULAM</a>
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">TRIVANDRUM</a>
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">KOLLAM</a>
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">KANNUR</a>
                  <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">KOTTAYAM</a>
                </div>
              </li>
              
            </ul>
          </div>
        
        </nav>
        
      
        <div class="container mt-5 mb-5">
            <div class="row justify-content-center">
              <div class="col-md-10">
                <div class="login-box">
                    <h1 class="banner_taital m-2">LOGIN</h1>
                  <form method="POST" action=".">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="username" class="form-label">Username</label>
                      <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <div class="mb-3">
                      <label for="inputPassword4" class="form-label">Password</label>
                      <input type="password" class="form-control" id="inputPassword4" name="password">
                    </div>
                    <button class="btn btn-primary btn-block" type="submit">Login</button>
                    <a href="{% url 'bank:register' %}" class="btn btn-info btn-block">Register</a>
                  </form>
                </div>
              </div>
            </div>
          </div>
           {% for msg in messages %}
          {{msg}}
          {% endfor %}


    <div class="header_right">
        <img  src="{% static 'images/banner-bg.png' %}" class="banner_img" style="position: absolute; top: 0px; right: 200px; max-width: 600px;" >
    </div>
    
    </div>
   
     <!--footer section start -->
     <div class="footer_section layout_padding">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-sm-6">
            <h4 class="about_text">About Financial</h4>
            <div class="location_text"><img src="{% static 'images/map-icon.png' %}"><span class="padding_left_15">Locations</span></div>
            <div class="location_text"><img src="{% static 'images/call-icon.png' %}"><span class="padding_left_15">+01 9876543210</span></div>
            <div class="location_text"><img src="{% static 'images/mail-icon.png' %}"><span class="padding_left_15">demo@gmail.com</span></div>
          </div>
          <div class="col-lg-3 col-sm-6">
            <h4 class="about_text">About Financial</h4>
            <p class="dolor_text">ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</p>
          </div>
          <div class="col-lg-3 col-sm-6">
            <h4 class="about_text">Instagram</h4>
            <div class="footer_images">
              <div class="footer_images_left">
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
              </div>
              <div class="footer_images_right">
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
                <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-sm-6">
            <h4 class="about_text">Newsletter</h4>
            <input type="text" class="mail_text" placeholder="Enter your email" name="Enter your email">
            <div class="subscribe_bt"><a href="#">Subscribe</a></div>
            <div class="footer_social_icon">
              <ul>
                <li><a href="#"><img src="{% static 'images/fb-icon1.png' %}"></a></li>
                <li><a href="#"><img src="{% static 'images/twitter-icon1.png' %}"></a></li>
                <li><a href="#"><img src="{% static 'images/linkedin-icon1.png' %}"></a></li>
                <li><a href="#"><img src="{% static 'images/youtub-icon1.png' %}"></a></li>
              </ul>
            </div>
          </div>
        </div>
        <!-- copyright section start -->
        <div class="copyright_section">
          <div class="copyright_text">Copyright 2019 All Right Reserved By <a href="https://html.design">Free HTML Templates</a></div>
        </div>
        <!-- copyright section end -->
      </div>
    </div>
    
    <!--footer section end -->
    
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script> 
</body>
</html>